### ISSUE TITLE
Calibrate cameras

### ISSUE THREAD

**Issue by jkleiber** [team401/high-key-2024#14]
@aidnem I'm creating this issue to track the work on camera calibration 

Ideally we will get a really good calibration and save all the calibration files (in a separate repo for this specific purpose) so we can swap them as needed. Ideally we'd be able to hot swap a camera at competition in under 5 minutes if something happens.

**Scope**:
- [x] Find a good camera calibration
- [x] Ensure that we can localize consistently with it
- [ ] Create a repository for it and upload it

**Comment by aidnem** [comment]
Last night at shop we:
 - calibrated a camera with nearly 500 snapshots in various angles and positions.
   - Next time (if we need to recalibrate) I would: consider getting more angular variety, try to more systematically fill in the space rather than taking a ton of snapshots near the same locations.
   - I'd like to see if having too many snapshots will have any adverse effects on performance or if it's purely more snapshots = better.
 - Began to test the camera with the HITL rig:
   - It seemed to detect apriltags decently, however:
   - Extremely laggy (this could just be the stream off the beelink)
   - Because of the lag, tried to get the robot code running to read network tables instead:
     - Had to comment out drive (no featureflag yet, let's add that)
     - Got robot code to run and 'hadNewMeasurement' was flickering on the Front-Left camera in network tables. HOWEVER: **no pose data was being sent to network tables.** This could either be a code issue or simply a lack of information (correct behavior). I'll inquire into this before next shop.

@jkleiber I'm trying something new here by documenting progress made on the ticket so that we can keep track of progress, make sure we're on time, and also hopefully avoid having a ton of information lost by keeping everything in my head. If it works I'm thinking we could make it the standard, writing a little mini-retrospective on each shop day so that everything is kept track of nicely.

**Comment by aidnem** [comment]
A single camera seems to output an estimated pose just fine in the sim right now (/AdvantageKit/Vision/Front-Left/LatestFieldToRobot is updated and semi-accurate), I'll look into it more but it seems to be a vision issue and not a code issue.

**Comment by jkleiber** [comment]
@aidnem I think having more calibration shouldn't affect performance - it will only affect camera intrinsic matrix accuracy.

I like the idea of keeping things documented in tickets, let's keep it going

**Comment by aidnem** [comment]
Yesterday I:
- Got a pose estimate from the camera in advantagescope (nice proof that it actually is functioning
- Tested the camera viewing april tags from various angles (at 640x480 it still looked decent, but hopefully higher resolution will allow us to reach higher range)
  - **TODO** - After higher resolutions are calibrated, test performance of higher resolution cameras to make sure it won't be too slow
- figured out how to enable/disable overlayroot
- updated photonvision to 2024.3.1
- Discovered that our configuration didn't save because overlayroot was on when it was created.
- **TODO** - Disable overlayroot, calibrate camera on highest resolution and on a medium resolution for performance testing, reenable overlayroot.

**Comment by aidnem** [comment]
Last night at shop we:
- Added an old radio to HITL because the new radio kept overheating and becoming borderline-unusable for the second half of shop. We were actually able to work the whole time due to this.
- Got a camera calibration with ~40 snapshots on the OV2311 for 1280x960 that *seems* roughly accurate, but we'll need to test it more once we can drive a robot around. Based on our rough measurements and math skills we estimated its accuracy to be within 5-10cm when sitting on its own side of the field, although our poor tape-measure skills could definitely have contributed to this error.
  - When I looked it up, the only number I could find for FOV was "75H", which I'm not sure what it means but it could be a 75 degree horizontal FOV, which would place the diagonal FOV near 90 degrees according to [this chart ](https://vrguy.blogspot.com/2013/04/converting-diagonal-field-of-view-and.html). The camera calibration though its FOV was 97 degrees or something, which is still probably pretty terrible but it might not be as bad as we thought.
- Uploaded the old calibrations and the new calibration to the controls drive (I made a new folder for high key camera configurations).
- Minh continued to integrate the shooter arm on HITL and it looked like all of the motors now work. I don't think she's gotten the sensor working yet but I could be wrong.

**Comment by aidnem** [comment]
<img width="348" alt="image" src="https://github.com/user-attachments/assets/73ec9f33-a298-478c-a1ad-9ec346300fb5">

[This](https://www.amazon.com/Arducam-Monochrome-Distortion-Microphones-Compatible/dp/B096ZSSCGH) is the only place I could find a field of view listed for our camera but I'm not sure what the H means 😭

**Comment by jkleiber** [comment]
@aidnem this looks like a 75 degree horizontal FOV to me. So near 90 diagonal makes sense - doesn't photon vision also report horizontal FOV? In any case the initial results are probably fine for now and we can figure out how to calibrate even better once bigger problems are behind us

**Comment by aidnem** [comment]
Okay makes sense. I'll check for a horizontal FOV in photonvision tonight in shop.

@jkleiber we're planning on having shop on Saturday as well, will you be in town for that? No worries if not but I'm just curious.

**Comment by jkleiber** [comment]
@aidnem I won't be back until really late on Saturday night, so I'll be there Monday

**Comment by aidnem** [comment]
Okay, good to know. Safe travels!
